http://elixir-lang.org/
http://elixir-lang.org/blog/2013/08/08/elixir-design-goals/
http://en.wikipedia.org/wiki/Elixir_%28programming_language%29
http://www.theerlangelist.com/2014/01/why-elixir.html
http://devintorr.es/blog/2013/01/22/the-excitement-of-elixir/
http://damienkatz.net/2008/03/what_sucks_abou.html
http://devintorr.es/blog/2013/06/11/elixir-its-not-about-syntax/
http://pygments.org/
